
export const RECEIVE_USER_TOKEN = 'RECEIVE_USER_TOKEN'

export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO'

export const DELETE_USRE_TOKEN = 'DELETE_USRE_TOKEN'

export const RECEIVE_WECHAT_AUTH_INFO = 'RECEIVE_WECHAT_AUTH_INFO'

// export const MODI_WECHA_IMG = 'MODI_WECHA_IMG'

export const ALI_MESSAGE_AUTH = 'ALI_MESSAGE_AUTH'

export const ALI_MESSAGE_INFO = 'ALI_MESSAGE_INFO'

export const MODI_ALI_MESSAGE_INFO = 'MODI_ALI_MESSAGE_INFO'

export const MODI_WECHAT_INFO ='MODI_WECHAT_INFO'

//-----服务管理
export const GET_GROUP_INFO = 'GET_GROUP_INFO'

export const GET_GROUP_ITEM_INFO = 'GET_GROUP_ITEM_INFO'

export const SAVE_SERVICE_INFO = 'SAVE_SERVICE_INFO'

export const MODI_SHOW_CURRENT ='MODI_SHOW_CURRENT'

export const MODI_SERVICE_STATUS = 'MODI_SERVICE_STATUS'

//用户管理页面-----------------------------
export const GET_APPLY_SERVICE_USER_LIST = 'GET_APPLY_SERVICE_USER_LIST'

export const SAVE_ACTIVE_INTENTION_USER_ID = 'GET_ACTIVE_INTENTION_USER_ID'

export const MODI_USER_REMARK = 'MODI_USER_REMARK'

export const GET_USER_AUDIT = 'GET_USER_AUDIT'

export const UPDATE_USER_AUDIT_INFO = 'UPDATE_USER_AUDIT_INFO'

export const GET_ALL_SERVICE_DEVICE = 'GET_ALL_SERVICE_DEVICE'

export const UPDATE_ALL_SERVICE_DEVICE = 'UPDATE_ALL_SERVICE_DEVICE'

export const UPDATE_CURRENT_AUDIT = 'UPDATE_CURRENT_AUDIT'